# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# AndroidX package structure.
android.useAndroidX=true
# Only keep the project's own R class (non-transitive).
android.nonTransitiveRClass=true
# compileSdk 35 高于 AGP 8.4.2 的测试版本，显式抑制提示
android.suppressUnsupportedCompileSdk=35
